In [1]:
import pandas as pd
import os

In [2]:
# Estou puxando o nome da pasta onde está armazenado os arquivos do projeto:
caminho_raw = r"C:\Users\caldo\OneDrive\Desktop\Projetos_GIT\project_01_brazilian_ecommerce\data\raw"

# Aqui faço uma simples correção das barras, troco a barra '\' pela '/':
caminho = caminho_raw.replace('\\','/') + '/'
print('Caminho base para os arquivos:')
print(caminho)
print()

# Aqui eu listo os arquivos CSV que estão presentes dentro da pasta 'raw':
lista = os.listdir(caminho)
print(lista)

Caminho base para os arquivos:
C:/Users/caldo/OneDrive/Desktop/Projetos_GIT/project_01_brazilian_ecommerce/data/raw/

['olist_customers_dataset.csv', 'olist_geolocation_dataset.csv', 'olist_orders_dataset.csv', 'olist_order_items_dataset.csv', 'olist_order_payments_dataset.csv', 'olist_order_reviews_dataset.csv', 'olist_products_dataset.csv', 'olist_sellers_dataset.csv', 'product_category_name_translation.csv']

In [3]:
# Agora eu irei criar o caminho dos arquivos referente a cada base de dados.
# Basicamente irei fazer um concatenação entre o caminho + nome do arquivo na raw:
caminhos = []
for arquivo in lista:
    caminho_completo = caminho + arquivo
    caminhos.append(caminho_completo)

for arquivo in caminhos:
    print(arquivo)

C:/Users/caldo/OneDrive/Desktop/Projetos_GIT/project_01_brazilian_ecommerce/data/raw/olist_customers_dataset.csv
C:/Users/caldo/OneDrive/Desktop/Projetos_GIT/project_01_brazilian_ecommerce/data/raw/olist_geolocation_dataset.csv
C:/Users/caldo/OneDrive/Desktop/Projetos_GIT/project_01_brazilian_ecommerce/data/raw/olist_orders_dataset.csv
C:/Users/caldo/OneDrive/Desktop/Projetos_GIT/project_01_brazilian_ecommerce/data/raw/olist_order_items_dataset.csv
C:/Users/caldo/OneDrive/Desktop/Projetos_GIT/project_01_brazilian_ecommerce/data/raw/olist_order_payments_dataset.csv
C:/Users/caldo/OneDrive/Desktop/Projetos_GIT/project_01_brazilian_ecommerce/data/raw/olist_order_reviews_dataset.csv
C:/Users/caldo/OneDrive/Desktop/Projetos_GIT/project_01_brazilian_ecommerce/data/raw/olist_products_dataset.csv
C:/Users/caldo/OneDrive/Desktop/Projetos_GIT/project_01_brazilian_ecommerce/data/raw/olist_sellers_dataset.csv
C:/Users/caldo/OneDrive/Desktop/Projetos_GIT/project_01_brazilian_ecommerce/data/raw/product_category_name_translation.csv

In [4]:
# Agora irei criar os dataframes referente aos seus respectivos arquivos na base:
df_customer = pd.read_csv(caminhos[0])
df_geolocalizacao = pd.read_csv(caminhos[1])
df_pedidos = pd.read_csv(caminhos[2])
df_itens_pedidos = pd.read_csv(caminhos[3])
df_ordem_pagamento = pd.read_csv(caminhos[4])
df_revisao_pedidos = pd.read_csv(caminhos[5])
df_produtos = pd.read_csv(caminhos[6])
df_vendedores = pd.read_csv(caminhos[7])
df_categoria_translacao = pd.read_csv(caminhos[8])

In [5]:
# Para todos os próximos blocos de código é basicamente aplicar a informação de metadados (data_ingestao):

In [6]:
df_customer['data_ingestao'] = pd.Timestamp.now()
df_customer.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,data_ingestao
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,2026-04-06 19:20:49.689070
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,2026-04-06 19:20:49.689070
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,2026-04-06 19:20:49.689070
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,2026-04-06 19:20:49.689070
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,2026-04-06 19:20:49.689070

In [7]:
df_geolocalizacao['data_ingestao'] = pd.Timestamp.now()
df_geolocalizacao.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state,data_ingestao
0,1037,-23.545621,-46.639292,sao paulo,SP,2026-04-06 19:20:49.711293
1,1046,-23.546081,-46.644820,sao paulo,SP,2026-04-06 19:20:49.711293
2,1046,-23.546129,-46.642951,sao paulo,SP,2026-04-06 19:20:49.711293
3,1041,-23.544392,-46.639499,sao paulo,SP,2026-04-06 19:20:49.711293
4,1035,-23.541578,-46.641607,sao paulo,SP,2026-04-06 19:20:49.711293

In [8]:
df_pedidos['data_ingestao'] = pd.Timestamp.now()
df_pedidos.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,data_ingestao
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,2026-04-06 19:20:49.725516
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,2026-04-06 19:20:49.725516
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,2026-04-06 19:20:49.725516
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,2026-04-06 19:20:49.725516
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,2026-04-06 19:20:49.725516

In [9]:
df_itens_pedidos['data_ingestao'] = pd.Timestamp.now()
df_itens_pedidos.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,data_ingestao
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,2026-04-06 19:20:49.741778
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,2026-04-06 19:20:49.741778
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,2026-04-06 19:20:49.741778
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,2026-04-06 19:20:49.741778
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,2026-04-06 19:20:49.741778

In [10]:
df_ordem_pagamento['data_ingestao'] = pd.Timestamp.now()
df_ordem_pagamento.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value,data_ingestao
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33,2026-04-06 19:20:49.754773
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39,2026-04-06 19:20:49.754773
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71,2026-04-06 19:20:49.754773
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78,2026-04-06 19:20:49.754773
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45,2026-04-06 19:20:49.754773

In [11]:
df_revisao_pedidos['data_ingestao'] = pd.Timestamp.now()
df_revisao_pedidos.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,data_ingestao
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59,2026-04-06 19:20:49.767063
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13,2026-04-06 19:20:49.767063
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24,2026-04-06 19:20:49.767063
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06,2026-04-06 19:20:49.767063
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53,2026-04-06 19:20:49.767063

In [12]:
df_produtos['data_ingestao'] = pd.Timestamp.now()
df_produtos.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,data_ingestao
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,2026-04-06 19:20:49.778273
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,2026-04-06 19:20:49.778273
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,2026-04-06 19:20:49.778273
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,2026-04-06 19:20:49.778273
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,2026-04-06 19:20:49.778273

In [13]:
df_vendedores['data_ingestao'] = pd.Timestamp.now()
df_vendedores.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state,data_ingestao
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP,2026-04-06 19:20:49.798134
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP,2026-04-06 19:20:49.798134
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ,2026-04-06 19:20:49.798134
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP,2026-04-06 19:20:49.798134
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP,2026-04-06 19:20:49.798134

In [14]:
df_categoria_translacao['data_ingestao'] = pd.Timestamp.now()
df_categoria_translacao.head()

,product_category_name,product_category_name_english,data_ingestao
0,beleza_saude,health_beauty,2026-04-06 19:20:49.811122
1,informatica_acessorios,computers_accessories,2026-04-06 19:20:49.811122
2,automotivo,auto,2026-04-06 19:20:49.811122
3,cama_mesa_banho,bed_bath_table,2026-04-06 19:20:49.811122
4,moveis_decoracao,furniture_decor,2026-04-06 19:20:49.811122

In [15]:
# Realizo agora o mesmo processo de criação dos caminhos para ingestão dos dados.
# Ideia é a mesma, caminho base + nome dos arquivos:
caminho_destino_base = "C:/Users/caldo/OneDrive/Desktop/Projetos_GIT/project_01_brazilian_ecommerce/data/1_bronze/"
caminho_destino = []

for arquivo in lista:
    caminho_destino.append(caminho_destino_base + arquivo)
    
print(caminho_destino[0])

C:/Users/caldo/OneDrive/Desktop/Projetos_GIT/project_01_brazilian_ecommerce/data/1_bronze/olist_customers_dataset.csv

In [16]:
# Com a lista dos caminhos concluidas, basta rodar o to_csv:
df_customer.to_csv(caminho_destino[0], index=False)
df_geolocalizacao.to_csv(caminho_destino[1], index=False)
df_pedidos.to_csv(caminho_destino[2], index=False)
df_itens_pedidos.to_csv(caminho_destino[3], index=False)
df_ordem_pagamento.to_csv(caminho_destino[4], index=False)
df_revisao_pedidos.to_csv(caminho_destino[5], index=False)
df_produtos.to_csv(caminho_destino[6], index=False)
df_vendedores.to_csv(caminho_destino[7], index=False)
df_categoria_translacao.to_csv(caminho_destino[8], index=False)